"""Add image support

Revision ID: 476460e6ea52
Revises: 7f5f98b183dd
Create Date: 2025-05-17 08:37:40.486111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476460e6ea52'
down_revision = '7f5f98b183dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
